[package]
name = "atopio-extra"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
surrealdb = { version = "2.4.0", default-features = false }
